// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST.SQLServerRepoLib;

namespace ST.SqlServerRepoLib.Migrations
{
    [DbContext(typeof(SupportTicketDbContext))]
    [Migration("20181217164534_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ST.SharedEntitiesLib.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("ProductId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("ST.SharedEntitiesLib.Severity", b =>
                {
                    b.Property<int>("SeverityId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("SeverityId");

                    b.ToTable("Severity");
                });

            modelBuilder.Entity("ST.SharedEntitiesLib.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .IsUnicode(false);

                    b.Property<int>("ProductId");

                    b.Property<int>("SeverityId");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("TicketId");

                    b.HasIndex("ProductId")
                        .HasName("IX_ProductId");

                    b.HasIndex("SeverityId")
                        .HasName("IX_SeverityId");

                    b.HasIndex("TicketId")
                        .HasName("IX_TicketId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ST.SharedEntitiesLib.Ticket", b =>
                {
                    b.HasOne("ST.SharedEntitiesLib.Product", "Product")
                        .WithMany("Tickets")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_dbo.Ticket_dbo.Product_ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ST.SharedEntitiesLib.Severity", "Severity")
                        .WithMany("Tickets")
                        .HasForeignKey("SeverityId")
                        .HasConstraintName("FK_dbo.Ticket_dbo.Severity_SeverityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
